image: oven/bun:latest

stages:
  - setup
  - check
  - build
  - docker

cache:
  key:
    files:
      - bun.lockb
  paths:
    - node_modules/
    - apps/*/node_modules/
    - packages/*/node_modules/
  policy: pull-push

install_dependencies:
  stage: setup
  script:
    - bun install --frozen-lockfile

lint_and_format:
  stage: check
  needs:
    - install_dependencies
  script:
    - bun run lint

build_app:
  stage: build
  needs:
    - install_dependencies
  script:
    - echo "Checking MongoDB URI..."

    - |
      if [ -z "$MONGODB_URI" ]; then
        echo "MONGODB_URI is NOT SET"
        exit 1
      fi
<<<<<<< HEAD
      echo "MONGODB_URI=$MONGODB_URI:+SET" > apps/web/.env.local
      bunx turbo build --filter=web
=======

    - echo "MONGODB_URI=$MONGODB_URI" > apps/web/.env.local

    - echo "===== .env.local ====="
    - cat apps/web/.env.local

    - echo "===== Current Directory ====="
    - pwd

    - echo "===== apps/web ====="
    - ls -la apps/web

    - bunx turbo build --filter=web

>>>>>>> efe09bb33370bd0bec7d3f26466e3ed842be4f0f
  artifacts:
    paths:
      - apps/web/.next/
    expire_in: 1 week

build_docker_image:
  stage: docker
  image: docker:latest

  services:
    - docker:dind

  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  needs:
    - build_app

  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

  script:
    - docker build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" .
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"

    - docker tag "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA" "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"

  only:
    - main
